- name: Prepare the setup
  hosts: ovn_hosts
  become: true
  tasks:
  - name: Start openvswitch
    systemd:
      name: openvswitch
      state: started

  - name: Delete old docker volumes
    shell: |
      docker volume prune -f

  - name: Delete old docker containers if any
    shell: |
      set -e
      cd {{ ovn_fake_multinode_target_path }}/ovn-fake-multinode
      export CHASSIS_PREFIX={{ node_name }}
      export CHASSIS_COUNT=100
      ./ovn_cluster.sh stop
      docker system prune -f

  - name: Create ovs bridges for ovn fake multinode
    shell: |
      set -e
      ovs-vsctl --if-exists del-br br-ovn -- --if-exists del-br br-ovn-ext
      ovs-vsctl add-br br-ovn -- add-br br-ovn-ext

  - name: Add nics to br-ovn if configured
    when: internal_iface is defined
    shell: |
      ovs-vsctl add-port br-ovn {{ internal_iface }}

  - name: Add nics to br-ovn-ext if configured
    when: external_iface is defined
    shell: |
      ovs-vsctl add-port br-ovn-ext {{ external_iface }}

  - name: Deploy stats collection script
    copy:
      src: "{{ rundir }}/log-collector.sh"
      dest: /tmp/log-collector.sh
      mode: '0744'

  - name: Deploy perf script
    copy:
      src: "{{ rundir }}/perf.sh"
      dest: /tmp/perf.sh
      mode: '0744'

  - name: Deploy process monitor script
    copy:
      src: "{{ rundir }}/process-monitor.py"
      dest: /tmp/process-monitor.py
      mode: '0744'
