- name: Install ovn-fake-multinode
  hosts: all
  tasks:
    - name: Pull latest containers
      shell: |
              set -e
              podman pull {{ registry_node }}:5000/ovn/ovn-multi-node
              podman tag {{ registry_node }}:5000/ovn/ovn-multi-node ovn/ovn-multi-node
