- name: Install ovn-tester
  hosts: tester_hosts
  tasks:
  - name: Copy ovn-tester image
    ansible.posix.synchronize:
      src: "{{ rundir }}/ovn-tester-image.tar"
      dest: "{{ ovn_fake_multinode_target_path }}/ovn-tester-image.tar"

  - name: Load latest containers
    ansible.builtin.shell: |
      podman load -i {{ ovn_fake_multinode_target_path }}/ovn-tester-image.tar
